taiga.host=https://api.taiga.io
taiga.username=javiergs
taiga.password=dyNnyc-2sugva-hugrun

GROQ_API_KEY=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
GROQ_SERVER=https://api.groq.com/openai/v1/chat/completions
GROQ_MODEL=llama-3.1-8b-instant
